CREATE TABLE IF NOT EXISTS clients (
id BIGINT NOT NULL PRIMARY KEY,
login VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
user_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS friends (
client_id BIGINT NOT NULL,
friend_id BIGINT NOT NULL
);